[theme]
base = "light"
primaryColor = "#D9672F"
backgroundColor = "#FCFAF6"
secondaryBackgroundColor = "#F2EADF"
textColor = "#172321"

[client]
showSidebarNavigation = false

[server]
headless = true
